import type {
  AdminEntityAction,
  AdminEntityKey,
  AdminFieldConfig,
  AdminUserRole,
} from "@/lib/admin/types";
import { ADMIN_SETTINGS_SINGLETON_ID } from "./defaults";

export interface AdminEntityDefinition {
  key: AdminEntityKey;
  label: string;
  singularLabel: string;
  description: string;
  table: string;
  primaryKey: string;
  listFields: string[];
  formFields: AdminFieldConfig[];
  searchColumns: string[];
  searchPlaceholder?: string;
  permissions: Record<AdminEntityAction, AdminUserRole[]>;
  singleton?: boolean;
  singletonId?: string;
  lookupKeys?: string[];
}

const roleOptions = [
  { value: "member", label: "Member" },
  { value: "imam", label: "Imam" },
  { value: "shura", label: "Shura" },
  { value: "admin", label: "Admin" },
  { value: "super_admin", label: "Super Admin" },
];

const languageOptions = [
  { value: "en", label: "English" },
  { value: "ar", label: "Arabic" },
  { value: "ur", label: "Urdu" },
  { value: "bn", label: "Bengali" },
  { value: "tr", label: "Turkish" },
  { value: "ms", label: "Malay" },
];

const managementTeamTypeOptions = [
  { value: "operations", label: "Operations" },
  { value: "facilities", label: "Facilities" },
  { value: "education", label: "Education" },
  { value: "outreach", label: "Outreach" },
  { value: "youth", label: "Youth" },
  { value: "finance", label: "Finance" },
  { value: "security", label: "Security" },
];

const taskPriorityOptions = [
  { value: "low", label: "Low" },
  { value: "normal", label: "Normal" },
  { value: "high", label: "High" },
  { value: "urgent", label: "Urgent" },
];

const taskStatusOptions = [
  { value: "todo", label: "To Do" },
  { value: "in_progress", label: "In Progress" },
  { value: "blocked", label: "Blocked" },
  { value: "completed", label: "Completed" },
  { value: "cancelled", label: "Cancelled" },
];

export const ADMIN_ENTITY_DEFINITIONS: Record<AdminEntityKey, AdminEntityDefinition> = {
  mosques: {
    key: "mosques",
    label: "Mosques",
    singularLabel: "Mosque",
    description: "Manage the mosque directory, contact information, and verification state.",
    table: "mosques",
    primaryKey: "id",
    listFields: ["name", "city", "state", "capacity", "is_verified"],
    searchColumns: ["name", "city", "state", "address"],
    searchPlaceholder: "Search mosques by name, city, or address",
    lookupKeys: [],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["super_admin"],
    },
    formFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "address", label: "Address", type: "textarea", required: true },
      { key: "city", label: "City", type: "text", required: true },
      { key: "state", label: "State", type: "text", required: true },
      { key: "country", label: "Country", type: "text", required: true },
      { key: "zip_code", label: "Zip Code", type: "text" },
      { key: "phone", label: "Phone", type: "tel" },
      { key: "email", label: "Email", type: "email" },
      { key: "website", label: "Website", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "image_url", label: "Image URL", type: "text" },
      { key: "facilities", label: "Facilities", type: "tags" },
      { key: "latitude", label: "Latitude", type: "number" },
      { key: "longitude", label: "Longitude", type: "number" },
      { key: "capacity", label: "Capacity", type: "number" },
      { key: "established_year", label: "Established Year", type: "number" },
      { key: "is_verified", label: "Verified", type: "boolean" },
    ],
  },
  prayer_times: {
    key: "prayer_times",
    label: "Prayer Times",
    singularLabel: "Prayer Time",
    description: "Manage daily adhan and iqama schedules for each mosque.",
    table: "prayer_times",
    primaryKey: "id",
    listFields: [
      "date",
      "mosque_id",
      "fajr_adhan",
      "dhuhr_adhan",
      "maghrib_adhan",
      "isha_adhan",
    ],
    searchColumns: [],
    lookupKeys: ["mosques"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["imam", "shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "mosque_id",
        label: "Mosque",
        type: "select",
        required: true,
        lookup: "mosques",
      },
      { key: "date", label: "Date", type: "date", required: true },
      { key: "fajr_adhan", label: "Fajr Adhan", type: "text" },
      { key: "fajr_iqama", label: "Fajr Iqama", type: "text" },
      { key: "sunrise", label: "Sunrise", type: "text" },
      { key: "dhuhr_adhan", label: "Dhuhr Adhan", type: "text" },
      { key: "dhuhr_iqama", label: "Dhuhr Iqama", type: "text" },
      { key: "asr_adhan", label: "Asr Adhan", type: "text" },
      { key: "asr_iqama", label: "Asr Iqama", type: "text" },
      { key: "maghrib_adhan", label: "Maghrib Adhan", type: "text" },
      { key: "maghrib_iqama", label: "Maghrib Iqama", type: "text" },
      { key: "isha_adhan", label: "Isha Adhan", type: "text" },
      { key: "isha_iqama", label: "Isha Iqama", type: "text" },
      { key: "jummah_time", label: "Jummah Time", type: "text" },
      { key: "jummah_iqama", label: "Jummah Iqama", type: "text" },
    ],
  },
  events: {
    key: "events",
    label: "Events",
    singularLabel: "Event",
    description: "Manage calendar entries, publishing state, and registration details.",
    table: "events",
    primaryKey: "id",
    listFields: ["title", "mosque_id", "event_type", "start_date", "is_published"],
    searchColumns: ["title", "description", "location"],
    searchPlaceholder: "Search events by title, description, or location",
    lookupKeys: ["mosques"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["imam", "shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "mosque_id",
        label: "Mosque",
        type: "select",
        required: true,
        lookup: "mosques",
      },
      { key: "title", label: "Title", type: "text", required: true },
      {
        key: "event_type",
        label: "Type",
        type: "select",
        options: [
          { value: "general", label: "General" },
          { value: "jummah", label: "Jummah" },
          { value: "lecture", label: "Lecture" },
          { value: "community", label: "Community" },
          { value: "youth", label: "Youth" },
          { value: "fundraising", label: "Fundraising" },
        ],
      },
      { key: "start_date", label: "Start", type: "datetime", required: true },
      { key: "end_date", label: "End", type: "datetime" },
      { key: "location", label: "Location", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "registration_required", label: "Registration Required", type: "boolean" },
      { key: "max_attendees", label: "Max Attendees", type: "number" },
      { key: "is_recurring", label: "Recurring", type: "boolean" },
      { key: "recurrence_pattern", label: "Recurrence Pattern", type: "text" },
      { key: "is_published", label: "Published", type: "boolean" },
    ],
  },
  announcements: {
    key: "announcements",
    label: "Announcements",
    singularLabel: "Announcement",
    description: "Manage mosque alerts, notices, and time-bound announcements.",
    table: "announcements",
    primaryKey: "id",
    listFields: ["title", "mosque_id", "priority", "published_at", "is_published"],
    searchColumns: ["title", "content"],
    searchPlaceholder: "Search announcements by title or content",
    lookupKeys: ["mosques"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["imam", "shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "mosque_id",
        label: "Mosque",
        type: "select",
        required: true,
        lookup: "mosques",
      },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "content", label: "Content", type: "textarea", required: true },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
          { value: "urgent", label: "Urgent" },
        ],
      },
      { key: "published_at", label: "Published At", type: "datetime" },
      { key: "expires_at", label: "Expires At", type: "datetime" },
      { key: "is_published", label: "Published", type: "boolean" },
    ],
  },
  imams: {
    key: "imams",
    label: "Imams",
    singularLabel: "Imam",
    description:
      "Manage imam profiles, biographies, contact details, and the primary mosque assignment shown across the app.",
    table: "imams",
    primaryKey: "id",
    listFields: ["name", "mosque_id", "title", "experience_years", "is_active"],
    searchColumns: ["name", "title", "bio", "education"],
    searchPlaceholder: "Search imams by name, title, or biography",
    lookupKeys: ["mosques", "profiles"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "profile_id",
        label: "Linked Profile",
        type: "select",
        lookup: "profiles",
      },
      {
        key: "mosque_id",
        label: "Primary Mosque",
        type: "select",
        lookup: "mosques",
        description:
          "Optional. Choose the main mosque appointment for this imam. Additional mosque links can be managed from Imam Appointments.",
      },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "title", label: "Title", type: "text" },
      { key: "specializations", label: "Specializations", type: "tags" },
      { key: "education", label: "Education", type: "textarea" },
      { key: "experience_years", label: "Experience Years", type: "number" },
      { key: "languages", label: "Languages", type: "tags" },
      { key: "bio", label: "Biography", type: "textarea" },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone", type: "tel" },
      { key: "appointed_date", label: "Appointed Date", type: "date" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  imam_appointments: {
    key: "imam_appointments",
    label: "Imam Appointments",
    singularLabel: "Imam Appointment",
    description:
      "Link imam profiles to one or more mosques, choose a primary appointment, and keep appointment history structured.",
    table: "imam_appointments",
    primaryKey: "id",
    listFields: [
      "imam_id",
      "mosque_id",
      "role_title",
      "appointed_date",
      "is_primary",
      "is_active",
    ],
    searchColumns: ["role_title", "notes"],
    searchPlaceholder: "Search appointments by role title or notes",
    lookupKeys: ["imams", "mosques"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["shura", "admin", "super_admin"],
      update: ["shura", "admin", "super_admin"],
      delete: ["shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "imam_id",
        label: "Imam",
        type: "select",
        required: true,
        lookup: "imams",
      },
      {
        key: "mosque_id",
        label: "Mosque",
        type: "select",
        required: true,
        lookup: "mosques",
      },
      {
        key: "role_title",
        label: "Role Title",
        type: "text",
        description:
          "Optional mosque-specific role title. Leave blank to use the imam profile title.",
      },
      { key: "appointed_date", label: "Appointed Date", type: "date" },
      { key: "ended_at", label: "Ended On", type: "date" },
      {
        key: "is_primary",
        label: "Primary Appointment",
        type: "boolean",
        description:
          "The primary appointment is used to scope the Imam Panel and headline the imam profile.",
      },
      { key: "is_active", label: "Active", type: "boolean" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  management_teams: {
    key: "management_teams",
    label: "Management Teams",
    singularLabel: "Management Team",
    description:
      "Organize mosque operations teams led by the imam locally or dispatched across mosques by Shura.",
    table: "management_teams",
    primaryKey: "id",
    listFields: ["name", "mosque_id", "team_type", "lead_profile_id", "is_active"],
    searchColumns: ["name", "description", "team_type"],
    searchPlaceholder: "Search teams by name, purpose, or type",
    lookupKeys: ["mosques", "profiles"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["imam", "shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "mosque_id",
        label: "Mosque",
        type: "select",
        required: true,
        lookup: "mosques",
      },
      { key: "name", label: "Team Name", type: "text", required: true },
      {
        key: "team_type",
        label: "Team Type",
        type: "select",
        required: true,
        options: managementTeamTypeOptions,
      },
      {
        key: "lead_profile_id",
        label: "Lead Profile",
        type: "select",
        lookup: "profiles",
      },
      { key: "description", label: "Description", type: "textarea" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  management_team_members: {
    key: "management_team_members",
    label: "Team Members",
    singularLabel: "Team Member",
    description:
      "Assign people under an imam or Shura-managed team and define what they are responsible for.",
    table: "management_team_members",
    primaryKey: "id",
    listFields: ["member_name", "team_id", "role_title", "profile_id", "is_active"],
    searchColumns: ["member_name", "role_title", "notes"],
    searchPlaceholder: "Search team members by name, role, or notes",
    lookupKeys: ["management_teams", "profiles"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["imam", "shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "team_id",
        label: "Management Team",
        type: "select",
        required: true,
        lookup: "management_teams",
      },
      { key: "member_name", label: "Member Name", type: "text", required: true },
      {
        key: "profile_id",
        label: "Linked Profile",
        type: "select",
        lookup: "profiles",
      },
      { key: "role_title", label: "Role Title", type: "text", required: true },
      { key: "responsibilities", label: "Responsibilities", type: "tags" },
      { key: "notes", label: "Notes", type: "textarea" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  mosque_tasks: {
    key: "mosque_tasks",
    label: "Mosque Tasks",
    singularLabel: "Mosque Task",
    description:
      "Dispatch, monitor, and complete mosque work across operations, programs, facilities, and compliance.",
    table: "mosque_tasks",
    primaryKey: "id",
    listFields: ["title", "mosque_id", "team_id", "status", "priority", "due_at"],
    searchColumns: ["title", "description", "task_type"],
    searchPlaceholder: "Search tasks by title, type, or status details",
    lookupKeys: ["mosques", "management_teams", "profiles"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["imam", "shura", "admin", "super_admin"],
    },
    formFields: [
      {
        key: "mosque_id",
        label: "Mosque",
        type: "select",
        required: true,
        lookup: "mosques",
      },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      {
        key: "task_type",
        label: "Task Type",
        type: "select",
        options: managementTeamTypeOptions,
      },
      {
        key: "team_id",
        label: "Team",
        type: "select",
        lookup: "management_teams",
      },
      {
        key: "assigned_to_profile_id",
        label: "Assigned To",
        type: "select",
        lookup: "profiles",
      },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: taskPriorityOptions,
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: taskStatusOptions,
      },
      { key: "due_at", label: "Due At", type: "datetime" },
      { key: "started_at", label: "Started At", type: "datetime" },
      { key: "completed_at", label: "Completed At", type: "datetime" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  donations: {
    key: "donations",
    label: "Donations",
    singularLabel: "Donation",
    description: "Manage donation records, status, and finance-related metadata.",
    table: "donations",
    primaryKey: "id",
    listFields: ["mosque_id", "amount", "donation_type", "status", "created_at"],
    searchColumns: ["donation_type", "transaction_id", "notes"],
    searchPlaceholder: "Search donations by type, transaction ID, or notes",
    lookupKeys: ["mosques"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["super_admin"],
    },
    formFields: [
      {
        key: "mosque_id",
        label: "Mosque",
        type: "select",
        required: true,
        lookup: "mosques",
      },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency", label: "Currency", type: "text" },
      { key: "donation_type", label: "Donation Type", type: "text" },
      { key: "payment_method", label: "Payment Method", type: "text" },
      { key: "transaction_id", label: "Transaction ID", type: "text" },
      { key: "is_anonymous", label: "Anonymous", type: "boolean" },
      { key: "is_recurring", label: "Recurring", type: "boolean" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "pending", label: "Pending" },
          { value: "completed", label: "Completed" },
          { value: "failed", label: "Failed" },
          { value: "refunded", label: "Refunded" },
        ],
      },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  posts: {
    key: "posts",
    label: "Posts",
    singularLabel: "Post",
    description: "Moderate posts, visibility rules, and publish state from one place.",
    table: "posts",
    primaryKey: "id",
    listFields: ["content", "mosque_id", "visibility", "likes_count", "is_published"],
    searchColumns: ["content", "category"],
    searchPlaceholder: "Search posts by content or category",
    lookupKeys: ["mosques"],
    permissions: {
      read: ["imam", "shura", "admin", "super_admin"],
      create: ["imam", "shura", "admin", "super_admin"],
      update: ["imam", "shura", "admin", "super_admin"],
      delete: ["imam", "shura", "admin", "super_admin"],
    },
    formFields: [
      { key: "content", label: "Content", type: "textarea", required: true },
      { key: "mosque_id", label: "Mosque", type: "select", lookup: "mosques" },
      {
        key: "visibility",
        label: "Visibility",
        type: "select",
        options: [
          { value: "public", label: "Public" },
          { value: "followers", label: "Followers" },
          { value: "private", label: "Private" },
        ],
      },
      { key: "post_type", label: "Post Type", type: "text" },
      { key: "category", label: "Category", type: "text" },
      { key: "image_url", label: "Image URL", type: "text" },
      { key: "metadata", label: "Metadata", type: "json" },
      { key: "is_published", label: "Published", type: "boolean" },
    ],
  },
  profiles: {
    key: "profiles",
    label: "Profiles",
    singularLabel: "Profile",
    description: "Review profiles, roles, activation state, and visibility metadata.",
    table: "profiles",
    primaryKey: "id",
    listFields: ["full_name", "email", "role", "mosque_id", "is_active"],
    searchColumns: ["full_name", "email", "username"],
    searchPlaceholder: "Search users by name, email, or username",
    lookupKeys: ["mosques"],
    permissions: {
      read: ["admin", "super_admin"],
      create: [],
      update: ["admin", "super_admin"],
      delete: ["super_admin"],
    },
    formFields: [
      { key: "id", label: "Profile ID", type: "text", readOnly: true },
      { key: "full_name", label: "Full Name", type: "text" },
      { key: "email", label: "Email", type: "email" },
      { key: "username", label: "Username", type: "text" },
      {
        key: "role",
        label: "Role",
        type: "select",
        required: true,
        options: roleOptions,
      },
      { key: "mosque_id", label: "Mosque", type: "select", lookup: "mosques" },
      { key: "phone", label: "Phone", type: "tel" },
      { key: "bio", label: "Biography", type: "textarea" },
      { key: "is_verified", label: "Verified", type: "boolean" },
      { key: "is_active", label: "Active", type: "boolean" },
      { key: "privacy_settings", label: "Privacy Settings", type: "json" },
      { key: "metadata", label: "Metadata", type: "json" },
    ],
  },
  settings: {
    key: "settings",
    label: "Settings",
    singularLabel: "Settings",
    description: "Control global modules, live behavior, and Shura permissions from a singleton config.",
    table: "admin_settings",
    primaryKey: "id",
    listFields: ["site_name", "default_timezone", "default_language", "updated_at"],
    searchColumns: ["site_name", "site_description", "contact_email"],
    permissions: {
      read: ["admin", "super_admin"],
      create: ["admin", "super_admin"],
      update: ["admin", "super_admin"],
      delete: [],
    },
    singleton: true,
    singletonId: ADMIN_SETTINGS_SINGLETON_ID,
    lookupKeys: [],
    formFields: [
      { key: "site_name", label: "Site Name", type: "text", required: true },
      { key: "site_description", label: "Site Description", type: "textarea" },
      { key: "contact_email", label: "Contact Email", type: "email" },
      { key: "support_phone", label: "Support Phone", type: "tel" },
      { key: "default_timezone", label: "Default Timezone", type: "text", required: true },
      {
        key: "default_language",
        label: "Default Language",
        type: "select",
        required: true,
        options: languageOptions,
      },
      {
        key: "date_format",
        label: "Date Format",
        type: "select",
        required: true,
        options: [
          { value: "MM/dd/yyyy", label: "MM/DD/YYYY" },
          { value: "dd/MM/yyyy", label: "DD/MM/YYYY" },
          { value: "yyyy-MM-dd", label: "YYYY-MM-DD" },
        ],
      },
      {
        key: "calculation_method",
        label: "Prayer Calculation",
        type: "select",
        required: true,
        options: [
          { value: "isna", label: "ISNA" },
          { value: "mwl", label: "Muslim World League" },
          { value: "egypt", label: "Egyptian General Authority" },
          { value: "makkah", label: "Umm Al-Qura" },
          { value: "karachi", label: "University of Karachi" },
        ],
      },
      {
        key: "notification_settings",
        label: "Notification Settings",
        type: "json",
      },
      { key: "privacy_settings", label: "Privacy Settings", type: "json" },
      { key: "module_settings", label: "Module Settings", type: "json" },
      { key: "shura_permissions", label: "Shura Permissions", type: "json" },
      { key: "metadata", label: "Metadata", type: "json" },
    ],
  },
};

export function getAdminEntityDefinition(entityKey: string): AdminEntityDefinition | null {
  if (!(entityKey in ADMIN_ENTITY_DEFINITIONS)) {
    return null;
  }

  return ADMIN_ENTITY_DEFINITIONS[entityKey as AdminEntityKey];
}

export function listAdminEntityDefinitions(): AdminEntityDefinition[] {
  return Object.values(ADMIN_ENTITY_DEFINITIONS);
}
